sudo: required
services: 
  - docker

before_install:
  - docker build -f Dockerfile.dev -t rastogiabhijeet/docker_react .

script:
  -  docker run rastogiabhijeet/docker_react npm run test -- --coverage
  